version: "3"
services:
    https-portal:
        image: steveltn/https-portal
        ports:
            - "80:80"
            - "443:443"
        links:
            - sap
        restart: always
        environment:
            DOMAINS: 'sap.ml -> http://sap:3000'
            STAGE: 'production'
            FORCE_RENEW: 'true'
        networks:
           - sap-network

    sap:
        container_name: SAP_Project 
        build:
            context: .
            dockerfile: Dockerfile
        labels:
            maintainer: "peace_data"
            e-mail: "peace_data@cryptolab.nl"
            version: "1.0"
            description: "Ruby on Rails project - SAP, RybyCon LLC"
        expose:
            - "3000"
        ports:
            - "3000:3000"
        depends_on:
            - mysqldb
        links:
            - mysqldb
        environment:
            COMPOSE_CONVERT_WINDOWS_PATHS: "true"
            COMPOSE_INTERACTIVE_NO_CLI: "true"
            DOCKER_HOST: "sap"
            ASPNETCORE_ENVIRONMENT: "Production"
            BASE_URL: 'https://sap.ml'
        restart: always
        networks:
           - sap-network
        volumes:
           - .:/var/www/sap

    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        labels:
            maintainer: "peace_data"
            e-mail: "peace_data@cryptolab.nl"
            version: "1.0"
            description: "Ruby on Rails project - SAP, RybyCon LLC"
        restart: always
        env_file:
            - .env
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
           - sap-network
           
networks:
    sap-network:
      driver: bridge