apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: MariaDB for RybyCon LLC
    e-mail: peace_data@cryptolab.nl
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
    maintainer: peace_data
    version: "1.0"
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mariadb-env
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: mariadb-env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: mariadb-env
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mariadb-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: mariadb-env
        - name: MYSQL_VERSION
          valueFrom:
            configMapKeyRef:
              key: MYSQL_VERSION
              name: mariadb-env
        - name: SAP_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SAP_SECRET_KEY
              name: mariadb-env
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY_BASE
              name: mariadb-env
        image: 'mariadb:'
        name: mariadb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-claim0
      restartPolicy: Always
      volumes:
      - name: mariadb-claim0
        persistentVolumeClaim:
          claimName: mariadb-claim0
status: {}
