apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Ruby on Rails project - SAP, RybyCon LLC
    e-mail: peace_data@cryptolab.nl
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
    maintainer: peace_data
    version: "1.0"
  creationTimestamp: null
  labels:
    io.kompose.service: sap
  name: sap
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: sap
status:
  loadBalancer: {}
